name: TestActions
on:
  pull_request :
    branches : [ main ]
  push :
    branches: [ main ]

jobs:

  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Create key.properties
        run: echo "API_KEY=${{ secrets.API_KEY }}" > key.properties

      - name: Run Spotless with Gradle
        run: ./gradlew spotlessApply

  test:
    name: Unit Test
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Setup Google Services
        run: |
          mkdir -p app/src/debug
          echo '${{ secrets.GOOGLE_SERVICES }}' > app/src/debug/google-services.json

      - name: Run unit tests
        run: ./gradlew clean :app:testDebugUnitTest